import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";
import { notFound } from "next/navigation";
import { routing } from "@/i18n/routing";
import type { Metadata } from "next";
import { estedad } from "../../fonts";
import Header from "@/components/layout/Header/Header";
import Footer from "@/components/layout/Footer/Footer";
import "../globals.css";



export const metadata: Metadata = {
  title: "MohammadParsaBahredar",
  description: "Generated by create next app",
};



export default async function LocaleLayout({children, params,}: {children: React.ReactNode; params: Promise<{ locale: string }>;}) {
  
  
  const { locale } = await params;

  if (!routing.locales.includes(locale as any)) {
    notFound();
  }

  const messages = await getMessages();
  return (
    <html
      className={`${locale === "fa" ? estedad.className : ""} h-full antialiased`}
      lang={locale}
      dir={locale === "fa" ? "rtl" : "ltr"}
    >
      <body className="dark:bg-[#262626]">
        <NextIntlClientProvider messages={messages}>
          <Header/>
          <main>
            {children}
          </main>        
          <Footer/>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
